drop table if exists accounts;

create table accounts (
    id int generated by default as identity,
    name varchar(100) not null,
    balance dec(15,2) not null,
    primary key(id)
);

insert into accounts(name,balance)
values('Bob',10000);

insert into accounts(name,balance)
values('Alice',10000);

create or replace procedure transfer(
sender int,
receiver int,
amount dec
)
language plpgsql
as $$
-- subtracting the amount from the sender's account
begin
update accounts
set balance = balance - amount
where id = sender;
-- adding the amount to the receiver's account
update accounts
set balance = balance +amount
where id = receiver;

commit;
end;$$

call transfer(1,2,1000);
select * from accounts;

create or replace procedure switch_rating(
	film1 varchar,
	film2 varchar
)
language plpgsql
as $$
declare 
	 temp_rating1 mpaa_rating;
	temp_rating2 mpaa_rating;
begin
	
	select rating into temp_rating1
	from film
	where title = film1;
	
	select rating into temp_rating2
	from film
	where title = film2;
	
	
	update film
	set rating =temp_rating2
	where title = film1;
		
	update film
	set rating = temp_rating1
	where title = film2;
	
commit;
end;$$