create table accounts(
    id int generated by default as identity,
    name varchar(100) not null,
    balance dec(15,3) not null,
    primary key(id)

);

insert into accounts(name,balance) values('Amir',1000);
insert into accounts(name,balance) values('Ali',2000);

begin;
update accounts
set balance = balance - 200 where id=1;
update accounts 
set balance = balance + 200 where id=2;
commit;

select * from accounts;

-- rollback before end of transaction
BEGIN;
UPDATE accounts SET balance=balance-150 Where id=2
UPDATE accounts SET balance=balance+150 Where id=1
rollback;


